/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 9
   Tile set      : C:\users\Public\Desktop\mushroom.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 9
#define mapHeight 9
#define mapBank 0

extern unsigned char map[];

/* End of MAP.H */
