/*

 WORLD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\users\Public\Desktop\mushroom.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define worldWidth 32
#define worldHeight 32
#define worldBank 0

extern unsigned char world[];

/* End of WORLD.H */
